spring:
  datasource:
    username: user
    password: password
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health,liveness,readiness
        base-path: /actuator