spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/smart-shorts-realm
          jwk-set-uri: http://keycloak:8080/realms/smart-shorts-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/smart-shorts-realm
        registration:
          keycloak:
            client-id: smart-shorts-realm-gateway-client
            client-secret: nwkLZMju8gmi2V4AfDfiyzKTBxSVxyKc
            authorization-grant-type: client_credentials