spring:
  cloud:
    gateway:
      routes:
        - id: eureka_route
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1
        - id: kafka_ui_route
          uri: lb://KAFKA-UI
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1
        - id: video-fragments-service-route
          uri: lb://VIDEO-FRAGMENTS-SERVICE
          predicates:
            - - Path=/video-aggregation-service/**
        - id: react_ui_fallback_route
          uri: lb://REACT-UI-SERVICE
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:30880/realms/smart-shorts-realm
          jwk-set-uri: http://keycloak:8080/realms/smart-shorts-realm/protocol/openid-connect/certs
        client:
          registration:
            keycloak:
              client-id: gateway-service
              client-secret: B8nzQlm0Plhd5NpfuSFsdoJ0laN5ffSQ
              authorization-grant-type: client_credentials
              scope: openid