spring:
  cloud:
    gateway:
      routes:
        - id: eureka_route
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1
        - id: kafka_ui_route
          uri: lb://KAFKA-UI
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1
        - id: react_ui_fallback_route
          uri: lb://REACT-UI-SERVICE
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/smart-shorts-realm
          jwk-set-uri: http://keycloak:8080/realms/smart-shorts-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/smart-shorts-realm
        registration:
          keycloak:
            client-id: smart-shorts-realm-gateway-client
            client-secret: nQQ5GBOInFuQbIaxW4nlT3u5KZjOkizk
            authorization-grant-type: client_credentials