spring:
  cloud:
    gateway:
      routes:
        - id: eureka_route
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1
        - id: kafka_ui_route
          uri: http://kafka-ui:8080
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1
        - id: video-aggregation-service-route
          uri: lb://VIDEO-AGGREGATION-SERVICE
          predicates:
            - Path=/video-aggregation-service/**
        - id: react_ui_fallback_route
          uri: lb://REACT-UI-SERVICE
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:30880/realms/smart-shorts-realm
          jwk-set-uri: http://keycloak:8080/realms/smart-shorts-realm/protocol/openid-connect/certs
        client:
          registration:
            keycloak:
              client-id: gateway-service
              client-secret: SkHGuaQdV3Q44TJNOHiR83LJYC35RRWp
              authorization-grant-type: client_credentials
              scope: openid