spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/smart-shorts-realm
          jwk-set-uri: http://localhost:8080/realms/smart-shorts-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/smart-shorts-realm
        registration:
          keycloak:
            client-id: smart-shorts-realm-gateway-client
            client-secret: BNDzI8RpAbNqRYTYQGTVStUENQaiSn67
            authorization-grant-type: client_credentials